version: 1.0.0.{build}
image: Ubuntu

configuration: Release
platform: x86

install:
- sh: >-
    sudo dpkg --add-architecture i386

    sudo apt-get update -qq

    sudo apt-get install -qq nasm:i386 build-essential gcc-multilib g++-multilib

before_build:
- ps: >-
    Write-Host "`tDownload CGSC libcom_plugin"

    Write-Host $pwd

    cd ../

    curl -k -o libcom_plugin.zip https://iswenzz.com:1337/github/gsclib/libcom_plugin.zip

    7z x libcom_plugin.zip | Out-Null

    ls

build_script:
- ps: >-
    Write-Host "`tBuilding gsclib"

    cd gsclib

    make