#pragma once

void ComPrintf();
void LINQ_All();
void LINQ_Where();
void LINQ_Any();
void LINQ_Min();
void LINQ_Max();
void LINQ_Last();
void LINQ_First();
void LINQ_Cast();
void LINQ_OfType();
void LINQ_Sort();
void LINQ_Average();
void LINQ_Count();
void LINQ_Sum();
void LINQ_Select();
void LINQ_Range();
void LINQ_Repeat();
void LINQ_Reverse();
