find_path(PCRE2_INCLUDE_DIR "pcre2.h")
find_library(PCRE2_LIB pcre2-8)

set(PCRE2_LIBS
	${PCRE2_LIB})

set(PCRE2_INCLUDE_DIRS
	${PCRE2_INCLUDE_DIR})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(PCRE2 DEFAULT_MSG PCRE2_LIBS PCRE2_INCLUDE_DIRS)
mark_as_advanced(PCRE2_LIBS PCRE2_INCLUDE_DIRS)

if(NOT TARGET PCRE2::PCRE2)
	add_library(PCRE2::PCRE2 INTERFACE IMPORTED)
    set_property(TARGET PCRE2::PCRE2 PROPERTY INTERFACE_LINK_LIBRARIES "${PCRE2_LIBS}")
	set_property(TARGET PCRE2::PCRE2 PROPERTY INTERFACE_INCLUDE_DIRECTORIES "${PCRE2_INCLUDE_DIRS}")
endif()
